<template>
  <v-btn icon variant="text" density="compact">
    <v-icon :icon="mdiHelpCircle" size="small"></v-icon>
    <v-menu
      activator="parent"
      location="bottom"
      offset="5"
      :close-on-content-click="false"
    >
      <v-sheet
        style="border: var(--app-border)"
        elevation="20"
        class="pa-3 help-sheet text-body-2"
      >
        <div>
          <strong>Raw Colors:</strong>
          <p>
            Base colors which material uses to generate the palette of colors.
            <br />
            They are not the final colors.
          </p>
        </div>
        <div class="mt-3">
          <strong>Primary Color:</strong>
          <p>
            Main color used as a source by material to generate other colors.
          </p>
        </div>
        <div class="mt-3">
          <strong>Modes:</strong>
          <ul>
            <li>
              Inherited (available only on material colors) : The color is fully
              generated from the primary color. It can not be chosen.
            </li>
            <li>Custom: Choose the color to generate from.</li>
            <li>
              Blend: Like custom except that the color is harmonized with the
              primary color.
            </li>
          </ul>
        </div>
        <div class="mt-3">
          <strong>Settings:</strong>
          <ul>
            <li>
              Surface different from background: By default the background and
              surface colors generated by material are the same. If set to true,
              the surface will be slightly different from the background.
            </li>
          </ul>
        </div>
      </v-sheet>
    </v-menu>
  </v-btn>
</template>

<script setup>
import { mdiHelpCircle } from '@mdi/js';
</script>

<style>
.help-sheet {
  max-width: 350px;
}
ul {
  list-style-position: inside;
}
</style>
